### ISSUE TITLE
Tutorial/welcome screen at the start of the world

### ISSUE THREAD

**Issue by jacksongeritz** [UQdeco2800/2021-studio-1#107]
# **Description**
Currently there isn't any welcome screen to the game. This will add in a tutorial as you start the game. This primarily adds in keyboard shortcuts that are not obvious (spear and lightning) but can be expanded to include additional information and background/storyline.
 
# **Milestones**
- [x] Create a basic sprite and intro level to represent the tutorial
- [x] Spawn platforms to the left of the world correctly
- [x] Ensure that that level always spawns first
- [x] Stop the tutorial level from spawning after the start of the game
- [x] Check functionality

**Completion Deadline:** Sept. 29th

# **Documentation**
https://github.com/UQdeco2800/2021-studio-1/wiki/Tutorial-Level

# **Members**
- Jackson Geritz (@jacksongeritz)
