### ISSUE TITLE
Increasing the speed of the giant based on the distance to the player

### ISSUE THREAD

**Issue by peter-tr** [UQdeco2800/2021-studio-1#108]
# **Description**
**Feature:** Team 2 - Map fixes and Aesthetic Upgrades, Wall of Death speed change #80 
**Task:** Increasing the speed of the giant based on the distance to the player #108

Currently, the player goes faster than the Wall of Death and the Death Giant, and as a result, the distance between the player will grow greatly as the player moves right.

This issue should make it so the Wall of Death and Death Giant speeds up depending on the distance between it and the player, to keep the game difficult and intense, and more interactive.

This will be completed by adding a new component that checks the distance between the player and Wall of Death and adjust the speed according. There is already the function setMaxSpeed() created in sprint 2 to assist in implementation.

# **Milestones**
- [x] Create new component class
- [x] Create function to calculate distance between Player and Wall of Death
- [x] Utilise function to change speed of Wall of Death and Giant
- [x] Check functionality
- [x] Unit testing

**Completion Deadline:** Oct. 1th
 
# **Documentation**
 
# **Members**
- Peter Tran (@peter-tr ) (Peter Tran)
