### ISSUE TITLE
Sprite design and animations.

### ISSUE THREAD

**Issue by WintonNeg** [UQdeco2800/2021-studio-1#13]
# **Description**
**Task:** [Player Sprite](#13).
**Feature:** [Player Movement, Gravity, & Moving Camera + Player Sprite](#5 )
 
Add in the character design and animations integrating Norse colour themes and warrior movement. Each team member will design a character sprite based on a Norse god. The most suitable design will be used as the initial character. The other character sprites designed will have the potential to be used in a `character select feature`, making the game have multiple playable characters. Alter the `game.entities.factories.PlayerFactory` class to render the png of the designed character. The `.assets.configs.player` JSON file should store the stats of the player to be cohesive to the gameplay.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a character sprite
- [x] Create a character animation
- [x] Choose which character sprite and animation to add to the game
 
**Completion Deadline:** Aug. 20
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)

 
# **Member**
- Winston Niogret (@WintonNeg) (@Winton)
- Sean Dolan (@devDolan) (Sean Dolan)
- Lauren Whitehead (@LaurenWhitehead) (Lauren Whitehead)
- Shenhui Zhu (@Shenhui77) (Shenhui Zhu)
- Pragun Ramesha (@Xodacan) (Pragun)
