### ISSUE TITLE
Ensure wall of death can dispose of spikes at bottom of screen

### ISSUE THREAD

**Issue by lucenas** [UQdeco2800/2021-studio-1#152]
# **Description**
**Task:** [Ensure wall of death can dispose of spikes at bottom of screen](#152 ).
**Feature:** Team 2 - Fancy backgrounds and the tutorial screen #148
 
Currently the wall of death does not fully dispose of all spikes on the screen. This can be fixed by increasing the size of the hitbox of the wall of death. 
 
# **Dependencies**
- [x] Godmode needed to test this is fixed (#155 )

# **Milestones**
- [x] Increase size of hitbox (Oct. 10)
- [x] Test that this has fixed the issue (Oct. 10)
 
**Completion Deadline:** Oct. 11

# **Documentation**
https://github.com/UQdeco2800/2021-studio-1/wiki/Map-Generation-and-Design
 
# **Member**
- Jackson Geritz (@jacksongeritz) (@Jackson Geritz)
- Sam Lucena (@CodePilot58) (Sam Lucena)
