### ISSUE TITLE
Add to tutorial level - story line like 'RUN'. Maybe make the giant run towards player?

### ISSUE THREAD

**Issue by CodePilot58** [UQdeco2800/2021-studio-1#153]
# **Description**
**Task:** Tutorial Level Storyline & Giant Run (#153).
**Feature:** Fancy backgrounds and the tutorial screen (#148)
 
Tutorial screen needs an overhaul to make the game juicier. A tutorial level will be created and a storyline will be added to the tutorial at the start of the game. At the end of the tutorial, the game will suddenly start with an enraged fire giant that will set the tone for the rest of the game.
 
## **Example (optional)**
- **End of tutorial**: There will be a single word at the end of the tutorial: "RUN!" with the fire giant speeding up and fully enraged. This will set the tone for the rest of the game.
 
# **Dependencies**
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add a tutorial level (Oct. 8)
- [x] Add storyline (Oct. 10)
- [x] Add scary effects to start the game (Oct. 12)
- [x] Test and release (Oct. 13)
 
**Completion Deadline:** Oct. 13
 
# **Documentation**
 
# **Member**
- Akash Iyer (@akash450) (@Akash Iyer)
- Jackson Geritz (@jacksongeritz) (@Jackson Geritz)
- Akash Iyer (@peter-tr) (@Peter Tran)
