### ISSUE TITLE
More LEVELS!

### ISSUE THREAD

**Issue by CodePilot58** [UQdeco2800/2021-studio-1#154]
# **Description**
**Task:** [More LEVELS!](#155).
**Feature:** Team 2 - Fancy backgrounds and the tutorial screen #148 

Currently the game only has 12 levels (some of which will need to be removed to make the game more fun/playable). If everyone makes 1-2 more levels the game will be much more interesting and some of the bad current levels can be removed.
 
# **Dependencies**
- [x] God mode might be useful for testing but not necessary (#155 )
 
# **Milestones**
- [x] Everyone has created the new levels (Oct. 13)
- [x] The new levels are vetted (Oct. 18)

**Completion Deadline:** Oct. 18

# **Documentation**

 
# **Member**
- Jackson Geritz (@jacksongeritz) (Jackson)
- Xaviour Greenhalgh (@XaviourG) (Xaviour D Greenhalgh)
- Akash Iyer (@akash450) (Akash Iyer)
- Sam Lucena (@CodePilot58) (Sam Lucena)
- Peter Tran (@peter-tr) (Peter Tran)
