### ISSUE TITLE
Team 4: Sprint 4 Entity Bug Fixes: disposal fireballs, death animation, sound changes

### ISSUE THREAD

**Issue by JLeTien** [UQdeco2800/2021-studio-1#156]
# **Description**
**Feature:** Disposal fireballs, Death animation, Sound changes

- **Disposal fireballs:** 
- **Sound:** 
- **Death animation:**
 
# **Dependencies**
Talking amongst the teams is critical. We need to conference with Team 2 to discuss the generation, Team 1 to discuss the player and how to manipulate the entity through the AreaManager, and all teams to discuss spritework and seamless integration into the final product.

-  **Enemy Proficiency** (@four-ts + @JLeTien + @GallagherN )
-  Sound (@neo-take-lucy )
- **RagEdit (@four-ts + @JLeTien + @GallagherN  + @neo-take-lucy)
 
# **Milestones**
List of steps that need to be completed for this task.

- [ ] 

**Completion Deadline:** Oct. 5th
 
# **Documentation**
- [ ] Write documentation for Sound
- [ ] Write documentation for RAGCMD
- [ ] Write documentation for Loader
- [ ] Write tutorial for ragEdit
- [ ] Write documentation for AreaManager, AreaService, and explain differences. Explain how to extend current functionality to make cooler. 
 
# **Member**
- Nathan Gallagher (@GallagherN)
- James Le Tien (@JLeTien)
- Tony Train (@four-ts)
- John Keegan (@neo-take-lucy)

**Comment by Dr2n** [comment]
Would like to see more detail added here before approval.

**Comment by GallagherN** [comment]
Yeah that's all good, sorry about that
