### ISSUE TITLE
Team 3 -Information display UI updates, main menu screen improvements, icons, scoring refinement, polish 🧊 and juice 🍰

### ISSUE THREAD

**Issue by JohnCom** [UQdeco2800/2021-studio-1#157]
# **Description** 

Task:  Game Polish 🧊 , Game Juice 🍰 -- Information display UI updates, main menu screen improvements, icons, UI improvements, scoring refinement, entity interactions
          #157  

### The Features: ⛰️ 🗻 

Team 3 will focus on game polish, bug fixing and implementing some small juicy features for sprint 4. 
The following are some main features to be developed in the game:

Game Polish 🧊  
Adding information to relevant screens associated with the game will be a focus of the sprint. This will include adding the current score and player name to the pause screen as well as potentially propagating some existing information to pop up screens (i.e. inventory / player lightning and spears). Code smells in sonar cloud will also be a focus of this sprint for some team members. 

Game Juice 🍰 
This is defined as anything that improves the payers experience / gameplay experience. Enabling the player to name themselves is expected to improve the players experience and hence will be a focus of the sprint. Adding some playable interactions with entities / enemies beyond the existing might also be a focus. Main screen nice features 👯.

Bug Fixing 🧷 🐛 🔧 
The team will also attempt to find bugs within existing features and existing implementation. The team will focus on resolving these issues by devoting about three days of development to testing and evaluation of studio wide features. 

### Example Output

Game Polish 
Adding information to respective UIPopups and game screens should improve the user experience as the user is expected to be more informed.  
Name input on main menu screen, expected to improve the players experience as they might relate to the name they are playing with. 

Game Juice 
Adding main screen dynamic changes should improve the players experience. 
Improving the randomised AI task is expected to improve the players experience.

Bug Fixing 
The game generally has some bugs that could be fixed to improve the player experience.
Bug fixing will initially focus on UI implementation and game information display issues then move to general gameplay elements if bugs continue to exist. 

### Dependencies 🔽 

-[] No bugs are introduced in sprint 4 that block the development of tasks.
-[] Functional game entities and UI elements. 

### Milestones and Due Dates 📅 

- [] Game Polish Tasks - by October 15
- [] Game Juice Tasks - by October 12
- [] Testing and bug fixing Tasks - October 19

**List of steps that need to be completed for this task:**

**Completion Deadline:** Sunday October 19 11:59pm -- All code and assets pushed to feature branch and main. 

**List of Sub tasks necessary to complete this ticket:**
- [x] #158
- [ ] #159
- [x] #160
- [x] #161
- [x] #162
- [x] #163
- [ ] #164
- [ ] #165
- [x] #166
- [x] #167
- [ ] #168
- [x] #169
- [ ] #170
- [ ] #171
- [ ] #172

# **Members** 👥 
- John Cominos (@JohnCom ) (John Cominos) 
- James De Raat (@JDR3008 ) (James De Raat)
- Manan Bhatia (@manan16007) (Manan Bhatia)
- Bach Truong (@bach-truong) (Bach Truong)
- Louis Denman (@LouisMDenman) (Louise Denman)

**Comment by Dr2n** [comment]
Love the emojis :D
