### ISSUE TITLE
Exit and pause event handling and UI button changes. ❗

### ISSUE THREAD

**Issue by JohnCom** [UQdeco2800/2021-studio-1#162]
**Description**

Exit button and pause button in the top right of the game screen to be changed. 

**Task List**

- [ ] Remove the exit button and replace with text saying that "esc" button exits the game. 
- [ ] Add an event for pressing "esc" to exit the game. 
- [ ] Remove the pause button and replace with text saying that "p" button pauses the game.
