### ISSUE TITLE
Add player death animation and music

### ISSUE THREAD

**Issue by WintonN** [UQdeco2800/2021-studio-1#173]
# **Description**
**Task:** [Refine player death](#173)
**Feature:** [Refining the death/Game over, Bug fixes, and Enemy sounds](#149)
 
- Refining the player death: Currently there is nothing other than a game over screen appearing when the player dies. The plan is to implement the player death animation that has already been designed and other aspects to make the death of the player have more impact. The player dying needs to be a major deterrent and a nuisance to make the player actively avoid dying.

## **Example (optional)**
- Player death: add death animation, maybe a fade to black or zoom in on the player as the death animation plays
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Implement death animation [Oct. 9]
- [ ] Implement a fade to black or zoom on death [Oct. 10]
- [ ] Refine the player death [Oct. 14]
 
**Completion Deadline:** Oct. 19
 
# **Documentation**
- Wiki pages
- Java docs
- UMLs
 
# **Member**
- Sean Dolan (@devDolan) (Sean Dolan)
- Winston Niogret (@WintonNeg) (Winton)
- Lauren Whitehead (@LaurenWhitehead) (Lauren Whitehead)
- Shenhui Zhu (@Shenhui77) (Shenhui Zhu)
