### ISSUE TITLE
Slope Collisions and Physics Implementation

### ISSUE THREAD

**Issue by CodePilot58** [UQdeco2800/2021-studio-1#21]
# **Description**
**Task:** Slope Collisions and Physics Implementation (#21).
**Feature:** Team 2 - Map Design & Generation + Wall of Death + Sprites for terrain(#4).
 
Implement the part of the terrain that the player will collide with, stopping them from falling through the world. This should be integrated into the Box2D physics system. The terrain will be made of platforms made with a similar approach to how the trees in the demo game are made. They will include at least the following components:
- `TextureRenderComponent`
- `PhysicsComponent`
- `ColliderComponent`

The platforms will be placed on one of three different height `lanes` above the `floor` level. This will help to make sure the player can always fit between platforms or be able to jump over enemies between platforms.

The platforms will also have a length that is a multiple of a standard unit, which will be the size of a platform's texture. For example, say a single block texture has a size of 16x16, then the platforms may be 16, 32, 48, 64, ... long.
 
# **Dependencies**
 
- [x] Random slope generation (#24)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a physics enabled object that the player may collide with (Aug 25)
- [x] Implement the random slope generation (Aug 28)
 
**Completion Deadline:** Aug. 31

# **Documentation**
- Wiki: [Map Generation and Design](../wiki/Map-Generation-and-Design)
 
# **Member**
- Sam Lucena (@CodePilot58) (Sam Lucena)
