### ISSUE TITLE
Create Platform and Floor Assets (Aug 21)

### ISSUE THREAD

**Issue by CodePilot58** [UQdeco2800/2021-studio-1#22]
Deadline: 21/08/2021
Responsible: @akash450
Final Design:
![image](https://user-images.githubusercontent.com/75708031/131426218-a59cb5ff-3809-405f-a953-4da5de342eda.png)
![image](https://user-images.githubusercontent.com/75708031/131426292-34399140-121b-480b-879c-1d035114c374.png)

# **Description**

**Task:** Creation of platform blocks and floor assets. (Aug 21) #22
**Feature:** Team 2 - Map Design & Generation + Wall of Death + Sprites for terrain (#4 ).

- Design and implementation of the floor and platform texture assets for character to walk on in the game.
- Integration into game
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design floor and platform assets
- [x] Integrate this into the current game engine
- [x] Check if platforms and floor are correctly spawning
- [x] Release

**Completion Deadline:** Aug. 21
 
# **Member**
- Akash Iyer (@akash450)
