### ISSUE TITLE
Code the wall of death (Aug 25)

### ISSUE THREAD

**Issue by CodePilot58** [UQdeco2800/2021-studio-1#23]
# **Description**

**Task:** Dynamic Procedural Generation of Map (Aug 31) #23
**Feature:** Team 2 - Map Design & Generation + Wall of Death + Sprites for terrain(#4 ).

- Implementation of the generation of the wall of death.
- Apply texture and animation to the NPC
- Implement hitbox for Wall of Death so that it goes through obstacles and other NPC while colliding with the player.
- Sets the player's health to 0 if collision detected.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create artwork and sprites for the Wall of Death
- [x] Convert sprites into a spritesheet and generate an altas file
- [x] Implement large NPC entity that is the height of the screen big
- [x] Program the Wall of Death to move toward the right direction indefinitely
- [x] Integrate this into the current game engine as a dynamic NPC
- [x] Cause the Wall of Death of instantly kill the player (sets player health to 0).
- [x] Ensure that the Wall of Death moves across the map without stopping and colliding with other objects.

**Completion Deadline:** Aug. 29
 
# **Member**
- Peter Tran (@peter-tr)
