### ISSUE TITLE
Map Generation (Aug 25)

### ISSUE THREAD

**Issue by CodePilot58** [UQdeco2800/2021-studio-1#24]
# **Description**

**Task:** Generation of Map (Aug 25) #24
**Feature:** Team 2 - Map Design & Generation + Wall of Death + Sprites for terrain(#4 ).

- Implementation of the generation of the terrain as the player moves through the world.  The world must load from a file that then spawns in all entities. Ideally this should be written such that this feature can be progressed into a complete procedural generation.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create level file
- [x] Read input from file
- [x] Spawn entities into game from file

**Completion Deadline:** Aug. 25
 
# **Member**
- Jackson Geritz (@jacksongeritz)
