### ISSUE TITLE
Team 2: Improve Wall of Death, Map Generation and level/theme progression

### ISSUE THREAD

**Issue by CodePilot58** [UQdeco2800/2021-studio-1#31]
# **Description**
**Feature:** Improve Wall of Death, Map Generation and level/theme progression #31

- [x] Addition to the wall of death - new fire wall which acts as a exact hitbox for the player
- [x] Screen change colour when approaching the wall of death
- [x] Map generation - Level / theme progression
- [x] Disposing of old maps once wall of death has passed
- [x] Wall of death sounds
- [x] Platforms / floors change for a changing theme

_changes 12/9_
Because of the changes to the game engine, map generation has changed. See #32 for details.
 
## **Example**
- **Wall of Death**
The hitbox for the giant is a bit ambiguous, so a new entity that looks like a wall of fire will be created that has a more easily seen barrier for the player to collide with. This will be rendered on top of the giant, and if the player collides with it they should die.
- **Screen Change**
As the player slows down and gets closer to the wall of death, the screen should get darker.
- **Map Generation**
The map generation should be automated by breaking the map down into small chunks that are selected randomly.
- **Disposing of old maps**
As entities are passed by the wall of death, they should be disposed of to relieve memory.
- **Changing theme**
To allow for the player to traverse many different areas in one game, may different themes should be made for the platforms, floors.
 
# **Dependencies**

# **Milestones**
List of tasks that need to be completed for this feature.
 
**Completion Deadline:** Sep 14.
 
# **Documentation**
 
# **Members**
- Jackson Geritz (@jacksongeritz) (Jackson)
- Xaviour Greenhalgh (@XaviourG) (Xaviour D Greenhalgh)
- Akash Iyer (@akash450) (Akash Iyer)
- Sam Lucena (@CodePilot58) (Sam Lucena)
- Peter Tran (@peter-tr) (Peter Tran)

**Comment by neo-take-lucy** [comment]
making level editor to assist in generating levels. Each level made in editor is small slivered "chunk", with "connections". Thus, the permutations of the game are then "chunk chose connections". If there are 30 chunks, and each chunk has 5 connections, 30 chose 5 is 142506. That's A LOT OF LEVELS MAN
