### ISSUE TITLE
Procedural Map Generation - Level Design

### ISSUE THREAD

**Issue by CodePilot58** [UQdeco2800/2021-studio-1#32]
# **Description**
**Feature:** Improve Wall of Death, Map Generation and level/theme progression #31
**Task**: Procedural Map Generation - Level Design #32 

_new plan_
This has been changed because of the changes by @neo-take-lucy. The new plan is to now:

- [x] Use the given load() funciton in AreaManager to load new sets of platforms, floors, enemies onto the world (each of these sets will be called a 'level')
- [x] Change the load() function to not delete everything in the current world before loading in another
- [x] Keep track of when to load a new level by adding an invisible entity to the end of each level, which when collided with by the player will call another load()
- [x] Use this invisible entity to dispose of the level when the wall of death has passed it

_old plan_
The map should generate in chunks, so that as the player moves through the world it is loaded in front of them. There will be many chunks to load from, randomly selected to create the illusion of an infinite map. These chunks may also have different themes, depending on other team's progress on background design.
 
**Completion Deadline:** Sep 14.
 
# **Documentation**
 
# **Members**
- Jackson Geritz (@jacksongeritz) (Jackson)
- Sam Lucena (@CodePilot58) (Sam Lucena)

**Comment by neo-take-lucy** [comment]
chunked levels with beginning and end conditions that determine which level to go to next

**Comment by CodePilot58** [comment]
Description updated to show changes in programming style
