### ISSUE TITLE
Team 1 - Attack animations, Player collision with entities, Power ups, game speed

### ISSUE THREAD

**Issue by WintonNeg** [UQdeco2800/2021-studio-1#33]
# **Description**
**Feature:** [Attack animations, Player collision with entities, Power ups, Game speed] (#33)
 
- **Player Collisions**: Make smoother player collisions player has when coming into contact with enemies and other entities. Currently the player collisions with other entities can be a bit odd. This is most likely due to the hit-boxes of the entities not being correctly line up with the textures and just being basic shapes (as can be seen in the debug mode). The player collisions can most likely be fixed by adding more complex hit-boxes.
- **Power Ups**: Spawn power ups into the game (such as shield, weapon, short duration invincibility, etc...) for the player to pick up and interact with. Spawning power ups will allow the player to perform more features than just running and trying to survive. For example, the player could pick up a shield power up which will allow them to survive one hit from an enemy entity without any repercussions. The power ups that will be added for now are a weapons (most likely a spear that can be thrown by the player), a shield that allows for one free hit from enemy entities, and lightning that kills all nearby enemy entities. Depending on time, more might be added, but others can also be added in a future sprint.
- **Animations**: Add animations for when the player collects a power up. Each power up will require a unique change in animation. For example, if the player picks up a shield, then the character sprite will change to be holding a shield for the player to recognise they are now holding a shield. Each power up will require new animations, with some also requiring editing of previous ones to make the effect from the power up visible to the player.
- **Game Speed**: Edit the game speed to be more enjoyable when playing. Currently, the game speed is too slow for the player which doesn't allow for a very enjoyable experience. The goal is to change the player speed to make the user experience more enjoyable while playing. This will involve changing the speed of the overall entities in the game, as well as the speed of the player.
 
# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.
 
- [x] #36 (@WintonNeg)(@LaurenWhitehead) 
- [x] #37 (@devDolan) (@WintonNeg)
- [x] #38 (@Shenhui77) (@devDolan) (@LaurenWhitehead)
- [x] #39 (@WintonNeg)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix the game speed (Sept. 8) 
- [x] Add base power up (Sept.  8)
- [x] Start editing the hit-boxes of entities (Sept. 8)
- [x] Finish Player Collisions (Sept.  12)
- [x] Finish adding Power ups (Sept.  12)
- [x] Add all Animations (Sept.  12)
 
**Completion Deadline:** Sept. 14
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- UML Diagrams for power ups 
- Wiki pages for power ups
- UML Diagram for entity collision 
- Wiki pages for entity collision and edit older wiki pages to encompass new logic
 
# **Member**
- Winston Niogret (@WintonNeg) (Winton)
- Sean Dolan (@devDolan) (Sean Dolan)
- Lauren Whitehead (@LaurenWhitehead) (Lauren Whitehead)
- Shenhui Zhu (@Shenhui77) (Shenhui Zhu)

**Comment by Dr2n** [comment]
More detail will be required for this ticket. Some things that could be added:

- Do you have any deadlines within the sprint?
- Who is responsible for each milestone?
- What power ups will be implemented and what will they do?
- Some more information about game speed (and what's currently wrong with it) would be helpful.
