### ISSUE TITLE
Team 4 - Level Editor, Terminal Commands, New Enemy

### ISSUE THREAD

**Issue by GallagherN** [UQdeco2800/2021-studio-1#34]
# **Description**
**Feature:** [Level Editor, Terminal Commands, New Enemy shooting projectiles] (#34)

- **Level Editor:** Create a level editor to make it easier in the long run to create more "levels" of the game. The use of this to create a text file with the scripts of the levels produced by everyone to append onto the current state of the game to make the game seem endless. Making them into text files makes it easier to call as it will have the exact load out of the level to be implemented. 
- **Terminal Commands:** The terminal commands are to be used while inside the game. Although they are not meant to affect the game in anyway from the casual player, it is designed to help speed up the process in testing certain elements. This will help by calling certain entities or levels to check how they operate with the player and/or other entities. This is also a great tool in testing the levels created to see if it would fit in the game as a versatile segment of the game. 
- **New Enemy:** The new enemy is going to be a fire entity that shoots fire balls at the player. It will have similar movements to the other two current enemies but the big difference is it will lock on to the player and shoot a fire ball, this ball will shoot at the location of the player as it was fired. The fire ball will then proceed in a straight line.
 
# **Dependencies**
Talking amongst the teams is critical. We need to conference with Team 2 to discuss the generation, Team 1 to discuss the player and how to manipulate the entity through the AreaManager, and all teams to discuss spritework and seamless integration into the final product.

-  #58 (@four-ts + @JLeTien)
-  #57 (@GallagherN)
- **Level Editor:** (@neo-take-lucy + @GallagherN)
- **Terminal Commands:** (@neo-take-lucy)
-  #56 (@JLeTien)
 
# **Milestones**
List of steps that need to be completed for this task.

- [x] New Enemy (9/9)
- [x] Documentation and merging current AreaManager with main (11/9)
- [x] Polishing Enemies (12/9)
- [ ] Terminal Commands (12/9)
- [ ] Level Editor (12/9)
 
**Completion Deadline:** Sept. 14
 
# **Documentation**
- [ ] Write documentation for Skeleton, Wolf, and Fire Enemy
- [ ] Write documentation for RAGCMD
- [ ] Write documentation for Loader
- [ ] Write tutorial for ragEdit
- [ ] Write documentation for AreaManager, AreaService, and explain differences. Explain how to extend current functionality to make cooler. 
 
# **Member**
- Nathan Gallagher (@GallagherN)
- James Le Tien (@JLeTien)
- Tony Train (@four-ts)
- John Keegan (@neo-take-lucy)

**Comment by Dr2n** [comment]
Please add to this ticket.

**Comment by Dr2n** [comment]
Would still like to see more detail in this ticket before approval.

**Comment by Dr2n** [comment]
Approved. Please also be sure to fit in some testing/evaluation on your new features as well.
