### ISSUE TITLE
Team 3 -- Level Backgrounds + possible designs -- General Improvements

### ISSUE THREAD

**Issue by JohnCom** [UQdeco2800/2021-studio-1#35]
# **Description**
**Task:** Level backgrounds, general game improvements -- UI descriptions, bugs, testing, score handling 
**Feature:** [Level backgrounds, general game improvements -- UI descriptions, bugs, testing, score](#35)
 
This sprint team three will focus on generating backgrounds for three different levels following established level themes by the studio. If another team is not also working on level designs, some members of team three might establish what a possible level could look like in terms of player, character, obstacle, giant and level platforms. Team three will also focus this sprint on changes to enemy AI logic and possibly implementing a game UI wrapper if time permits. There are a small number of overflowing tasks from sprint 1, such as a score handler class and a small amount of UI screen design, which will be completed. Further to this team three will focus on fixing game bugs for the purpose of more seamless integration of features. Furthermore there will be a testing focus for any new content created -- some established tests for UI will include mocked scenarios if time permits. 

## **Example Level background**
Discuss with studio and team 2 (since they are working on level themes also) about possible level themes and designs. 
Conceptualise some level themes prior to discussion to present / discuss. 
After finalising some level themes create level in image editor of choice (Photoshop). 
Present iterations to studio -- for feedback. 

## **Example general improvement** 
Fixing issues / bugs that have risen from feature integrations. I.e. Bugs that have risen as a consequence of merging feature branches.
Improvements to enemy AI.
Improving some testing -- UIComponent.  

# **Dependencies**
No real dependencies to execute background design tasks other than discussing concepts with studio and other teams. 
No dependencies for general improvements. 
  
# **Milestones**
List of steps that need to be completed for this task.
- [x] #50 1
- [ ] #50 2 
- [x] #50 3
- [x] #51
- [ ] Six more bugs fixed from list of bugs (Sunday 12th September) #51
- [ ] #52
- [ ] #53
- [x]  Score handling class integration and testing (Wed 8th September) #26
 
**Completion Deadline:** - Tuesday 14th September
 
Tasks 
- [x] #50 1
- [x] #50 2
- [ ] #50 3
- [x] #51 Three bugs person 1
- [ ] #51 Three bugs person 2
- [ ] #51 Three bugs person 3
- [ ] #52  
- [ ] #53 
 
# **Documentation**
- _Level design document to be placed here_
 
# **Members**
- John Cominos (@JohnCom ) (John Cominos)
- James De Raat (@JDR3008 ) (James De Raat)
- Manan Bhatia (@manan16007) (Manan Bhatia)
- Bach Truong (@bach-truong) (Bach Truong)
- Louis Denman (@LouisMDenman) (Louis Denman)
