### ISSUE TITLE
Team 2 - Map Design & Generation + Wall of Death + Sprites for terrain

### ISSUE THREAD

**Issue by CodePilot58** [UQdeco2800/2021-studio-1#4]
# **Description**
**Task:** Map Design & Generation + Wall of Death + Sprites for terrain (#4).
**Feature:**

- Implement procedural generation for the sloping hills and wall of death. The procedural generation will ensure randomisation of the game where no two runs will be on the same terrain. 
- Include sprites for both the wall of death and the terrain. The wall of death will be the first main obstacle to be added during the first sprint, and more enemies will be implemented in future sprints.
 
## **Example**
- **Terrain**: 
The terrain will be implemented as a mathematical function, to simulate rolling hills. The terrain should ideally get more difficult/complex as you get further along
- **Wall of death**: 
Will be made into a wall of fire that moves through the map, on collision with the wall, the player will die.
 
# **Dependencies**
- [x] Overall art style and theme of the game 

For Testing:
- [x] Collisions with and preventing falling through the ground
- [x] Camera following player and allowing appropriate player movement
 
# **Milestones**
List of tasks that need to be completed for this feature.
- [x] #8
- [x] #21
- [x] #22
- [x] #9
- [x] #23
- [x] #24
- [x] #25
- [x] Integration into Game (Aug. 27)
- [x] Feature testing (Aug 30)
 
**Completion Deadline:** Aug. 31
 
# **Documentation**
- [Main wiki page of feature](../wiki/Map-Design-Generation-and-Wall-of-death)
 
# **Members**
- Jackson Geritz (@jacksongeritz) (Jackson)
- Xaviour Greenhalgh (@XaviourG) (Xaviour D Greenhalgh)
- Akash Iyer (@akash450) (Akash Iyer)
- Sam Lucena (@CodePilot58) (Sam Lucena)
- Peter Tran (@peter-tr) (Peter Tran)
