### ISSUE TITLE
Wall of Death 2.0 (Visual FX, Fire & Smog Trail, Sound FX)

### ISSUE THREAD

**Issue by XaviourG** [UQdeco2800/2021-studio-1#41]
# **Description**

**Task:** Wall of Death 2.0 (Visual FX, Fire & Smog Trail, Sound FX)(#41 )
**Feature:** Team 2: Improve Wall of Death, Map Generation and level/theme progression(#31 ).

- Slowing the wall of death, stepping back its starting position, and making it delete level it 'consumes'.
- Expansion of wall of death, making the screen behind it a trail of fire and smog
- Adding SFX to the wall of death
- Making the screen shake, darken, saturate, and SFX intensify the closer you are to the wall of death.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Slow Wall of Death  (@peter-tr )
- [x] Move WoD back / make it start moving later. (@peter-tr )
- [x] Animate Fire Trail (Silhouette) (@XaviourG )
- [x] Colour Animated Fire Trail (@XaviourG )
- [x] Add Vertical Smog to Animation (@XaviourG )
- [x] #45 (@akash450 )
- [x] Implement New Trail as wall of death & make giant solely visual entity. (@peter-tr )
- [x] Make wall of death depose anything behind it. (@peter-tr )
- [x] Implement SFX (@akash450 )
- [x] Create 'state' that triggers when player close to wall of death (@peter-tr )
- [x] Make 'state' trigger a screen wide colour filter (Darker more saturated) FX (@XaviourG )
- [x] Make 'state' trigger shaking screen FX (@XaviourG )
- [x] Make 'state' trigger intensification of fire SFX (@akash450 )

**Completion Deadline:** Sep. 14

# **Member**
- Peter T (@peter-tr )
- Xaviour G (@XaviourG )
- Akash L (@akash450 )

**Comment by XaviourG** [comment]
Uncertainty regarding screen filters, postprocessing with libgdx might be and inefficient use of time.

**Comment by XaviourG** [comment]
Beautiful stuff gents, done and dusted!
