### ISSUE TITLE
Produce Sound FX: Walking, Fire Raging

### ISSUE THREAD

**Issue by akash450** [UQdeco2800/2021-studio-1#45]
# **Description**
**Task:** [Sound FX - Walking & Fire](#45).
**Feature:** [Team 2: Improve Wall of Death, Map Generation and level/theme progression](#31  )
 
Add sound effects for the giant wall of death as it is walking and also for the fire coming out of it. The sound generation will be done in 8-bit via 'ChipTone' to keep with the retro style of the game.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create SFX for walking giant
- [x] Create SFX for fire
- [x] Integrate into the game
 
**Completion Deadline:** Sept. 5
 
# **Documentation**
- [Main description of feature](../issues/31)
- [JavaDoc](JavaDoc/Location/Package/Class)

 
# **Member**
- Akash Iyer (@akash450)
