### ISSUE TITLE
Team 1 - Player Movement, Gravity, & Moving Camera + Player Sprite

### ISSUE THREAD

**Issue by devDolan** [UQdeco2800/2021-studio-1#5]
# **Description**
**Feature:** [Player Movement, Gravity, & Moving Camera + Player Sprite](#5 )
 
Add in the character design and animations integrating Norse colour themes and warrior movement. Each team member will design a character sprite based on a Norse god. The most suitable design will be used as the initial character. The other character sprites designed will have the potential to be used in a `character select feature`, making the game have multiple playable characters. Alter the `game.entities.factories.PlayerFactory` class to render the png of the designed character. The `.assets.configs.player` JSON file should store the stats of the player to be cohesive to the gameplay.

Implementation of gravity into the game engine and player movement to transition from the initial "top-down" play style to a "left-right" play style. Gravity will give entities functions such as jumping, floating or gliding. For the initial sprint, the initial character will be able to jump. This will require working with `game.physics.components` which integrate [Box2d](https://box2d.org/documentation/) modules.

The dynamic camera, associated with character movement, will track the player's movement in the map. It should move left, right, up and down with our character. This requires implementation and alterations to the components in `game.player` working cohesively with `game.screens.MainGameScreen` and its render components.
 
## **Examples**
-**Movement**: When a key (SPACE, W or up-arrow) is pressed the player will perform a jump.

-**Gravity**: All entities that have the applied gravity function will fall back down if in the air (i.e jumping, dropping down). Note: Some entities (created in future features) may have flight (i.e dragons, bosses, etc.).
 
# **Dependencies**
Listed below are all dependencies for this issue.
 
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] Team 2 - Map generation. (#4)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] 5 unique character sprite prototypes (Aug. 20).
- [x] Evaluate and decide on most suitable initial character (Aug. 20).
- [x] Gravity and Player movement (Aug. 25).
- [x] Character Animations (Aug. 25).
- [x] Moving camera (Aug. 28).
 
**Completion Deadline:** Aug. 31
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Winston Niogret (@WintonNeg) (@Winton)
- Sean Dolan (@devDolan) (Sean Dolan)
- Lauren Whitehead (@LaurenWhitehead) (Lauren Whitehead)
- Shenhui Zhu (@Shenhui77) (Shenhui Zhu)
- Pragun Ramesha (@Xodacan) (Pragun)

**Comment by WintonNeg** [comment]
Description
Task: Task Name.
Feature: Feature which this tasks contributes to implementing

A one paragraph description of the task on which you will work. It should briefly explain what will be done (e.g. "Implement an armour component"). This includes textual explanations of the work. (e.g. "Armour inherits from Component and will add an event handler to the player entity so that the armour takes damage rather than the player. Different types of armour will have different durability. Once the armour is broken (durability reaches zero), it will no longer take damage and more attacks on the player will cause it to lose health.")

Example (optional)
Part: Depending on the task, you may want to provide some examples of how it would play out in the game. See next point for example...
Armour Benefits: Players can wear different classes of armour. Armour takes damage until it breaks. Armour cannot be healed but can be replaced. If a player is wearing armour, its health is not affected when it takes damage unless the armour is broken.
Dependencies
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

 Dependency 1 (#xx)
 Dependency 2 (#xx)
e.g.

 Texture needs to be created for armour laying on map.
 Texture needs to be created for player wearing armour.
 Textures need to be created for partially, and then fully, broken armour.
 Mechanism needs to be implemented for armour to be placed onto map.
Milestones
List of steps that need to be completed for this task.

 Step 1 (Aug. 19)
 Step 2 (Aug. 20)
 Step 3 (Aug. 23) #3
 Step 4 (Aug. 23)
Completion Deadline: Aug. 31

e.g.

 Initial design of Armour created and documented on wiki (Aug. 19). #2
 Unit tests implemented for Armour (Aug. 20).
 Armour class implemented and tested (Aug. 23).
 Documentation of Armour updated on wiki (Aug. 23).
Documentation
Main description of feature
JavaDoc
...
Member
Name (GitHub Username) (Slack Handle)
Darren Fu (@Dr2n ) (Darren Fu)
Henry Burgess (@henry-burgess) (Henry Burgess)

**Comment by WintonNeg** [comment]
# **Description**
**Task:** [Task Name](#2).
**Feature:** [Feature which this tasks contributes to implementing](#2)
 
A one paragraph description of the task on which you will work. It should briefly explain what will be done (e.g. "Implement an armour component"). This includes textual explanations of the work. (e.g. "`Armour` inherits from `Component` and will add an event handler to the player entity so that the armour takes damage rather than the player. Different types of armour will have different durability. Once the armour is broken (durability reaches zero), it will no longer take damage and more attacks on the player will cause it to lose health.")
 
## **Example (optional)**
- **Part**: Depending on the task, you may want to provide some examples of how it would play out in the game. See next point for example...
- **Armour Benefits**: Players can wear different classes of armour. Armour takes damage until it breaks. Armour cannot be healed but can be replaced. If a player is wearing armour, its health is not affected when it takes damage unless the armour is broken.
 
# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.
 
- [ ] Dependency 1 (#xx)
- [ ] Dependency 2 (#xx)
 
e.g.
- [x] Texture needs to be created for armour laying on map.
- [ ] Texture needs to be created for player wearing armour.
- [ ] Textures need to be created for partially, and then fully, broken armour.
- [ ] Mechanism needs to be implemented for armour to be placed onto map.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Aug. 19)
- [ ] Step 2 (Aug. 20)
- [ ] #3
- [ ] Step 4 (Aug. 23)
 
**Completion Deadline:** Aug. 31
 
e.g.
- [x] #2
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Darren Fu (@Dr2n ) (Darren Fu)
- Henry Burgess (@henry-burgess) (Henry Burgess)
