### ISSUE TITLE
ragEdit Todo and Bugs

### ISSUE THREAD

**Issue by neo-take-lucy** [UQdeco2800/2021-studio-1#60]
Feel free to add your own To Dos (ideas) and bugs that you find. If you find a bug, please also send me a video on slack, and if you can, try to recreate it. 

Todo:
- [ ] fix -macro
- [ ] make SpawnCommand (proper)
- [ ] add in buttons for Zoom and Scrollup/Scrolldown
- [ ] add in the ability to spawn powerups (see #62)

Bugs:
- [ ] some problem with delete and undo? i dunno

**Comment by neo-take-lucy** [comment]
yeh killem

**Comment by neo-take-lucy** [comment]
you are the worst software developer known to man
