### ISSUE TITLE
Cohesive Wall of Death Aesthetic

### ISSUE THREAD

**Issue by XaviourG** [UQdeco2800/2021-studio-1#68]
# **Description**
The current wall of death is aesthetically discordant, as has been revealed via the sprint 2 user tests. The death giant needs to be updated both in resolution and colour scheme to better fit the smog wall and overall game aesthetic.

 
# **Milestones**
List of tasks that need to be completed for this feature.
- [x] Design goal visual, colour scheme, etc. Create a vision to achieve.
- [x] Recolour the Death Giant
- [x] Redesign the death giant animation
- [x] Redraw death giant
- [x] Implement new death giant
- [x] User Test new Wall of death aesthetic
- [ ] Refine wall of death wiki page

 
**Completion Deadline:** Sep. 27
 
# **Documentation**
- [Main wiki page of feature](../wiki/Map-Design-Generation-and-Wall-of-death)
 
# **Members**
- Xaviour Greenhalgh (@XaviourG) (Xaviour D Greenhalgh)

**Comment by XaviourG** [comment]
ezy
