### ISSUE TITLE
Team 1 - Player Aesthetic Overhaul and Gameplay Improvement

### ISSUE THREAD

**Issue by WintonNeg** [UQdeco2800/2021-studio-1#71]
# **Description**
**Feature:** [Team 1 - Player and Power Ups Aesthetic Overhaul and Gameplay Improvement](#71)
 
- Player animations overhaul: The plan is to add in more animation and change some of the existing animations which will help make the game feel smoother and improve the immersion. The character animations (running, jumping, etc...) will be redone to seem more realistic which will make the game feel a lot smoother. Since the game revolves around the player running, and the main premise of the game is the player running, this is the main priority. More animations for the power ups, such as showing the shield and spears breaking, having an animation where the player has both the spear and the shield, etc... Another animation to implement is animations when the player gets damaged as there currently is no distinct or noticeable indicator for the player losing health. Having a small knock-back animation and having the screen flash red would help the player notice they have been hit. Implementation would involve altering `PlayerFactory` and the player's main components;`PlayerActions`, `AnimationRenderComponent`, `PhysicsComponent` and `PowerUpsComponent`. New movement frames need to be added in the `Odin` spritesheet and frames to their corresponding power up animation.

- Power ups GUI: Currently, there is no way to show the user what keys activate the power up and how much they have used their power ups. Both the spear and shield have 3 uses and the lightning has one use, but the player does not know how many uses they have left as there are no visual indicators present on the screen. The idea is to add a GUI to the main game screen which will display the uses of the power ups and how many uses are remaining for each individual example. The HUD/GUI will be displayed in a non-obscuring location on screen. There should be 3 icons, one for each power up; `Lightning`, `Shield` and `Spear`. The icons should indicate whether the player is currently has the power up available, a number of uses for multi-use power ups and which key to press to `activate` the power up.

- Fixing power ups: Our team implemented the current power ups in Sprint 2, however they are a bit buggy. We couldn't figure out a way to spawn in entities in real time while the game is running, so the spear and lightning power ups have some _**interesting**_ implementation. However, we recently learned how to spawn in entities in real time. Therefore, the goal of this section is to reimplement the power ups with this new method which should fix some issues in the game and make the game a bit smoother. An idea for this is to also change the spear. We could have the spear stick into the wall and allow the player to use the spear as a sort of self-placed platform (shoot it into the wall and jump off of it). This would be done by setting the `gravity scale` of the spear to 0 once it collides with a platform. The spear currently has a bug where it sometimes kills more than one entity (possibly when it hits two enemies at the same time) - this issue will also need to be fixed.

- Game speed/difficulty: Currently, a lot of the studio members feel as though the game is a bit slow and thus boring. Although we could increase the speed of the player and of other monsters, this wouldn't make the game that much more interesting. The plan for this is to increase the speed of the game over time which will also increase the difficulty and enjoyment received from the game. We will be testing different variants of speed groups for entities and decide on the one which maintains consistent play flow, has the ability to linearly increase the difficulty over time and remains most efficient.
 
## **Example (optional)**
- Player animations overhaul: [Running animation](https://lukeotley.files.wordpress.com/2020/02/runcycle6.gif), [Jumping animation](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1a7f43fd-bc71-4b9d-b06a-fd8c71f74fe1/d7e1xvl-450d13cd-3839-497a-959e-7c1e2a5845a5.gif?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzFhN2Y0M2ZkLWJjNzEtNGI5ZC1iMDZhLWZkOGM3MWY3NGZlMVwvZDdlMXh2bC00NTBkMTNjZC0zODM5LTQ5N2EtOTU5ZS03YzFlMmE1ODQ1YTUuZ2lmIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.xFXiV2TLjIpS8zx9ZYYZL1JdYToBJw8I66aK1etymKY), wounded animations, power up animations, wounded sound.

- Power ups GUI: each power up would have an icon representation (lightning bolt, shield and a spear) and it would be highlighted or greyed out depending on whether it is available to the player or not. The icon will also contain the number of uses and the activation key; `K` for spear and `L` for lightning. The `shield`'s icon may slowly crack on each collision to display its uses.

- Fixing power ups: have the spear and lightning spawn upon the event being triggered by the player - spear spawns when player presses `K` and lighting spawns when player presses `L`, having the spear stick to walls and being able to jump on it.

- Game speed/difficulty: similar to jetpack joyride, slowly speed up over the course of the game, becoming more and more difficult to survive
 
# **Dependencies**
 
- [x] #73 (@devDolan) (@LaurenWhitehead) (@Shenhui77) (@WintonNeg)
- [x] #74 (@devDolan) (@Shenhui77)
- [x] #75 (@WintonNeg) (@devDolan) (@LaurenWhitehead) (@Shenhui77)
- [x] #76 (@WintonNeg) (@LaurenWhitehead)
 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Make a decision about the animations of the player (Sept. 17)
- [x] Fix one of the power ups (Sept. 20)
- [x] Have a simple power ups GUI (Sept. 21)
- [x] Have one set of player animations complete (Sept. 22)
- [x] Fix the second power up (Sept. 24)
- [x] Have the power ups GUI completed (Sept. 26)
- [x] Game speed/difficulty complete (Sept. 26)
- [x] Finish power up animations (Sept. 26)
- [x] Add new spear functionality - sticking to walls, etc... (Sept. 30)
- [x] Finish animations (Oct. 3)

 
**Completion Deadline:** Oct. 3
 
# **Documentation**
- Wiki Documentation - edit the power ups design and technical pages once the changes have been made
- Wiki Documentation - edit the player movement and player design pages once the changes have been made
- Wiki Documentation - page for power ups GUI
- Wiki Documentation - page about the game speed and the difficulty of the game (maybe work with team 2 for this as they are working on the speed of the giant this sprint)
- UML Diagrams for the power ups
- JavaDocs for any new methods and classes created
- Tests and recording of tests
- Task and feature tickets - add comments to the task and feature tickets describing progress made while working on the task until it is complete
 
# **Member**
- Sean Dolan (@devDolan) (Sean Dolan)
- Winston Nioget (@WintonNeg) (Winton)
- Lauren Whitehead (@LaurenWhitehead) (Lauren Whitehead)
- Shenhui Zhu (@Shenhui77) (Shenhui Zhu)
