### ISSUE TITLE
Player Animations Overhaul 

### ISSUE THREAD

**Issue by WintonNeg** [UQdeco2800/2021-studio-1#73]
# **Description**
**Feature:** #71 
 
- Player Animations overhaul: The plan is to add in more animation and change some of the existing animations which will help make the game feel smoother and improve the immersion. The character animations (running, jumping, etc...) will be redone to seem more realistic which will make the game feel a lot smoother. Since the game revolves around the player running, and the main premise of the game is the player running, this is the main priority. More animations for the power ups, such as showing the shield and spears breaking, having an animation where the player has both the spear and the shield, etc... Another animation to implement is animations when the player gets damaged as there currently is no distinct or noticeable indicator for the player losing health. Having a small knockback animation and having the screen flash red would help the player notice they have been hit.
 
## **Example (optional)**
- Player animations overhaul: [Running animation](https://lukeotley.files.wordpress.com/2020/02/runcycle6.gif), [Jumping animation](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1a7f43fd-bc71-4b9d-b06a-fd8c71f74fe1/d7e1xvl-450d13cd-3839-497a-959e-7c1e2a5845a5.gif?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzFhN2Y0M2ZkLWJjNzEtNGI5ZC1iMDZhLWZkOGM3MWY3NGZlMVwvZDdlMXh2bC00NTBkMTNjZC0zODM5LTQ5N2EtOTU5ZS03YzFlMmE1ODQ1YTUuZ2lmIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.xFXiV2TLjIpS8zx9ZYYZL1JdYToBJw8I66aK1etymKY), wounded animations, power up animations, wounded sound
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Make a decision about the animations of the player (Sept. 17)
- [x] Have one set of player animations complete (Sept. 22)
- [x] Finish power up animations (Sept. 26)
- [x] Finish animations (Oct. 3)

 
**Completion Deadline:** Oct. 5
 
# **Documentation**
- Wiki Documentation - edit the power ups design and technical pages once the changes have been made
- Wiki Documentation - edit the player movement and player design pages once the changes have been made
 
# **Member**
- Sean Dolan (@devDolan) (Sean Dolan)
- Winston Nioget (@WintonNeg) (Winton)
- Lauren Whitehead (@LaurenWhitehead) (Lauren Whitehead)
- Shenhui Zhu (@Shenhui77) (Shenhui Zhu)
