### ISSUE TITLE
Fixing Power Ups 

### ISSUE THREAD

**Issue by WintonNeg** [UQdeco2800/2021-studio-1#75]
# **Description**
**Feature:** #71
 

- Fixing power ups: Our team implemented the current power ups in Sprint 2, however they are a bit buggy. We couldn't figure out a way to spawn in entities in real time while the game is running, so the spear and lightning power ups have some _**interesting**_ implementation. However, we recently learned how to spawn in entities in real time. Therefore, the goal of this section is to reimplement the power ups with this new method which should fix some issues in the game and make the game a bit smoother. An idea for this is to also change the spear. We could have the spear stick into the wall and allow the player to use the spear as a sort of self-placed platform (shoot it into the wall and jump off of it). The spear currently has a bug where it sometimes kills more than one entity (possibly when it hits two enemies at the same time) - this issue will also need to be fixed.
 
## **Example (optional)**
- Fixing power ups: have the spear and lightning spawn upon the event being triggered by the player - spear spawns when player presses `K` and lighting spawns when player presses `L`, having the spear stick to walls and being able to jump on it

# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix one of the power ups (Sept. 20)
- [x] Have a simple power ups GUI (Sept. 21)
- [x] Fix the second power up (Sept. 24)
- [x] Have the power ups GUI completed (Sept. 26)
- [x] Finish power up animations (Sept. 26)
- [x] Add new spear functionality - sticking to walls, etc... (Sept. 30)
 
**Completion Deadline:** Oct. 5
 
# **Documentation**
- Wiki Documentation - edit the power ups design and technical pages once the changes have been made
- Wiki Documentation - edit the player movement and player design pages once the changes have been made
- JavaDocs for any new methods and classes created
- Tests and recording of tests
- Task and feature tickets - add comments to the task and feature tickets describing progress made while working on the task until it is complete
 
# **Member**
- Sean Dolan (@devDolan) (Sean Dolan)
- Winston Nioget (@WintonNeg) (Winton)
- Lauren Whitehead (@LaurenWhitehead) (Lauren Whitehead)
- Shenhui Zhu (@Shenhui77) (Shenhui Zhu)
