### ISSUE TITLE
Game Speed/Difficulty 

### ISSUE THREAD

**Issue by WintonNeg** [UQdeco2800/2021-studio-1#76]
# **Description**
**Feature:** #71
 
- Game speed/difficulty: Currently, a lot of the studio members feel as though the game is a bit slow and thus boring. Although we could increase the speed of the player and of other monsters, this wouldn't make the game that much more interesting. The plan for this is to increase the speed of the game over time which will also increase the difficulty and enjoyment received from the game.
 
## **Example (optional)**
- Game speed/difficulty: similar to jetpack joyride, slowly speed up over the course of the game, becoming more and more difficult to survive
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Make player start slowly and speed up when beginning to run/after getting hit
- [x] Make the player and entities speed up over time
- [x] Game speed/difficulty complete (Sept. 26)
 
**Completion Deadline:** Oct. 5
 
# **Documentation**
- Wiki Documentation - edit the player movement and player design pages once the changes have been made
- Wiki Documentation - page about the game speed and the difficulty of the game (maybe work with team 2 for this as they are working on the speed of the giant this sprint)
- JavaDocs for any new methods and classes created
- Tests and recording of tests
- Task and feature tickets - add comments to the task and feature tickets describing progress made while working on the task until it is complete
 
# **Member**
- Sean Dolan (@devDolan) (Sean Dolan)
- Winston Nioget (@WintonNeg) (Winton)
- Lauren Whitehead (@LaurenWhitehead) (Lauren Whitehead)
- Shenhui Zhu (@Shenhui77) (Shenhui Zhu)
