### ISSUE TITLE
Background/floor changes to worlds and world selection more random

### ISSUE THREAD

**Issue by akash450** [UQdeco2800/2021-studio-1#78]
# **Description**
The platforms have been redesigned for each 'world' or level in the game but the floor is constant since the first sprint. Hence, to fit the aesthetics of each level, the floors must be correspondingly designed. Backgrounds must also be designed to fit the colour scheme of each level as currently, the background is a plain blue colour.

# **Milestones**
List of tasks that need to be completed for this feature.
- [x] Design visualisation, based on platform colour scheme.
- [x] Design more floors (similar to the first design of floor but with some aesthetic tweaks for each level)
- [x] User testing on floor designs
- [x] #79
- [x] User Test aesthetic of the backgrounds, how well it fits.
- [x] Release

**Completion Deadline:** Oct. 04
 
# **Documentation**
 
# **Members**
- Xaviour Greenhalgh (@XaviourG) (Xaviour D Greenhalgh)
- Akash Iyer (@akash450) (Akash Iyer)
