### ISSUE TITLE
Design backgrounds for each world.

### ISSUE THREAD

**Issue by akash450** [UQdeco2800/2021-studio-1#79]
# **Description**
Backgrounds must be designed to fit the colour scheme of each level as currently, the background is a plain blue colour. These backgrounds will be inspired by natural settings in each of the Norse worlds except for Asgard, which is planned as a background of Odin's palace. These will be pixelated and their opacity will be made slightly transparent so that it does not blend in with the platforms and floor (looks like a background).

# **Milestones**
List of tasks that need to be completed for this feature.
- [x] Design visualisation goal, based on platform colour scheme.
- [x] Design backgrounds with pixelation
- [x] User testing on backgrounds
- [x] Redesign backgrounds as required
- [x] Release into game

**Completion Deadline:** Oct. 4
 

# **Members**
- Xaviour Greenhalgh (@XaviourG) (Xaviour D Greenhalgh)
- Akash Iyer (@akash450) (Akash Iyer)
