### ISSUE TITLE
Team 3 - UI content and implementation -- AI variant -- High Score

### ISSUE THREAD

**Issue by JohnCom** [UQdeco2800/2021-studio-1#82]
# **Description** 

Task:  [To improve and develop select UI content -- Enemy AI variant -- High Score implementation]

The Feature:

The UI for the game needs to have some focus for additional content screen creation and information display. This sprint team three will focus on improving the UI and adding additional UI screens such as a high score screen, game over screen as well as adding appropriate information to relevant existing pop ups. This general approach to implementation and design will be to focus on improving the user experience. This will involve liaising with other teams.

Having an additional enemy AI variant will be a focus of this sprint such that the deliverable will compliment existing AI enemy implementations in a unique way and one that improves the player experience and overall gameplay. 

Team 3 will also revise existing screen and level designs in line with studio feedback and team feedback and thought processes.  

The team is also yet to fully discuss and finalise scope for the sprint.

### Example Output

**High Score:**
The high score screen will track the highest score achieved from any single player across any played instance and place there name at a location on the screen. The high score layout will be shown in select places associated with typical screen interaction such as the main screen, during gameplay and possibly pause / banner oriented display.   

**Additional Information and UI content:**
Some of the existing screens already developed such as - pause screen and score screen need additional information displayed in line with what is typically shown on these screens. I.e. The pause screen can show player health, active score, time since level start. 

**AI Variant:**
To develop a unique enemy AI response from enemies in the game that will enhance gameplay and experience.  

### Dependencies

- Information is predetermined for display on screens, designs are predetermined and understood.
- No other dependencies to execute tasks.

### Milestones and Due Dates

**List of steps that need to be completed for this task:**

- [ ] Score variation on interaction with enemies 
- [x] Score and health display background   
- [x] Connect mute button event  
- [x] High score leaderboard  
- [x] Game ended screen  
- [x] Force lock resolution on game start
- [ ]  Extra AI variant implementation
- [ ] Significant integration 1
- [ ] Significant integration 2

**Completion Deadline:** Sunday October 3 11:59pm -- All code and assets pushed to feature branch. 

**List of Sub tasks necessary to complete this ticket:**
- [ ] Score variation on interaction with enemies 
- [x] Score and health display background   
- [x] Connect mute button event  
- [x] High score leaderboard  
- [x] Game ended screen  
- [x] Force lock resolution on game start
- [ ]  Extra AI variant implementation
- [ ] Significant integration 1
- [ ] Significant integration 2
 
# **Members**
- John Cominos (@JohnCom ) (John Cominos)
- James De Raat (@JDR3008 ) (James De Raat)
- Manan Bhatia (@manan16007) (Manan Bhatia)
- Bach Truong (@bach-truong) (Bach Truong)
- Louis Denman (@LouisMDenman) (Louise Denman)

**Comment by Dr2n** [comment]
Please add team label and assignees to this ticket.

**Comment by applebyter** [comment]
Inappropriate feature ticket. The UI work is too vague. The AI work is completely unrelated to the other parts of this ticket. This should be at least 3 different tickets.
