### ISSUE TITLE
Score variation on interaction with enemies

### ISSUE THREAD

**Issue by JohnCom** [UQdeco2800/2021-studio-1#83]
Implement the ability for the score to change as the player interacts with enemies and entities throughout the game.

**Task List:**

- [ ] Decide and discuss what elements and interactions should go in the game.
- [ ] Refine / Update the score handler class. 
- [ ] Implement the events / triggers associated with interactions. I.e. jumping on enemy + X amount. 
- [ ] Test

Score events discussed:

Enemy is killed -- then fixed increase.
When colliding with enemy --- then fixed decrease.
If on spikes then score decrease.
