### ISSUE TITLE
Connect mute button event

### ISSUE THREAD

**Issue by JohnCom** [UQdeco2800/2021-studio-1#85]
Add functionality to the mute event in the game:

**Task list:**

- [ ] Find the existing mute event in the game (MainMenuActions --- onMute()). 
- [ ] Change the asset picture also (on and off). 
- [ ] Disable global sound in this event. 
- [ ] Test.
