### ISSUE TITLE
Extra AI variant implementation

### ISSUE THREAD

**Issue by JohnCom** [UQdeco2800/2021-studio-1#89]
**Implement a unique responsive enemy behavioural AI variant that compliments existing AI classes:**

**Task list:**

- [ ] Design and discuss possible behaviour for enemy AI with other teams. 
- [ ] Implement AI variant using existing game engine structure or unique implementation that integrates with system well. 
- [ ] Test (a lot) -- Write tests.
