### ISSUE TITLE
Team 4 - Enemy Proficiency + Sound + RagEdit

### ISSUE THREAD

**Issue by GallagherN** [UQdeco2800/2021-studio-1#93]
# **Description**
**Feature:** Enemy Proficiency + Sound + RagEdit

- **Enemy Proficiency:** Adding some things to the current enemies as well as some quality of life stuff such as, death animations, animations for the fire spirit, knockback to the player, improve movement and the current collision hitboxes.
- **Sound:** Creating a soundboard for the game with background music to make the game more immersive to play and have related sound effects for the actions and state of the game.
- **RagEdit:** Create a tutorial for ragedit so multiple people can create their own slices of levels to see in the game as well as have a drop down box to select what world type the creator wants their level to be selected in. As well as other quality of life things to help things become easier as the game progresses
 
# **Dependencies**
Talking amongst the teams is critical. We need to conference with Team 2 to discuss the generation, Team 1 to discuss the player and how to manipulate the entity through the AreaManager, and all teams to discuss spritework and seamless integration into the final product.

-  **Enemy Proficiency** (@four-ts + @JLeTien + @GallagherN )
-  Sound (@neo-take-lucy )
- **RagEdit (@four-ts + @JLeTien + @GallagherN  + @neo-take-lucy)
 
# **Milestones**
List of steps that need to be completed for this task.

- [ ] #105  (19/9)
- [ ] #104 (21/9)
- [ ] #103 (24/9)
- [ ] #102 (20/9)
- [ ] #101 (19/9)
- [ ] #100 (23/9)
- [ ] #99 (22/9)
- [ ] #98 (20/9)
- [ ] #97 (24/9)
- [ ] #66 (20/9)
 
**Completion Deadline:** Oct. 5th
 
# **Documentation**
- [ ] Write documentation for Sound
- [ ] Write documentation for RAGCMD
- [ ] Write documentation for Loader
- [ ] Write tutorial for ragEdit
- [ ] Write documentation for AreaManager, AreaService, and explain differences. Explain how to extend current functionality to make cooler. 
 
# **Member**
- Nathan Gallagher (@GallagherN)
- James Le Tien (@JLeTien)
- Tony Train (@four-ts)
- John Keegan (@neo-take-lucy)

**Comment by Dr2n** [comment]
Please link subtasks and milestones to this feature ticket.

**Comment by GallagherN** [comment]
Okay will do, no I just grouped them together, I can individually do them separately
